### ISSUE TITLE
Command for adding links to pictures automatically

### ISSUE THREAD

**Issue by Benno2000** [SoftVarE-Group/SlideTemplate#63]
A command like `\pic` for including pictures and automatically adding a link to them. Therefore, the link gets stored in a txt-file with the same name as the picture (like already used in the SPL-Slides).

**Comment by Benno2000** [comment]
@tthuem Wouldn't it actually be easier to use `\pic{<image-file>}{<image-link>}` or is there a reason to store the link in a separate txt-file like in the SPL lecture?

**Comment by EagleoutIce** [comment]
It's definitely easier if you want to use the same image multiple times for multiple presentations.

**Comment by tthuem** [comment]
Storing the link in a file is better, as files are typically included multiple times and thus links have to be changed at multiple positions (when links change). Also, it is much easier to include a picture because one does not have to search for a previous usage. This proved very helpful for SPL.

In addition, we can later on use that to create a list of all images and their links for the handout. This is sometimes needed depending on the license the picture is published with.
